### ISSUE TITLE
dev: tox fails with matplotlib on Windows

### ISSUE THREAD

**Issue by ScottSoren** [ixdat/ixdat#10]
I am not able to run tests with tox on Windows which import anything from ixdat, since they crash when matplotlib is imported. Even the trivial test
```
def test_blank_measurement(): 

    from ixdat.measurements import Measurement
```
fails in tox. 

It does not matter whether I call tox from Anaconda Prompt or from git bash. 

The key line of the error message is 
`AttributeError: module 'sip' has no attribute 'setapi'`
The full error message (from Anaconda Prompt) is below.

The only constructive answer I could find googling this was https://stackoverflow.com/questions/64291087/matplotlib-module-sip-has-no-attribute-setapi, which suggests limiting matplotlib version to =3.2. However, I tried this and it didn't work.

Importing matplotlib is of course no problem normally. It seems to be a dependency issue - that tox installs the wrong `sip` and/or `matplotlib`. In the Anaconda prompt, they are both in the Anaconda3 site packages:
```
(base) PS C:\Users\scott\git\ixdat> python
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.__file__
'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\matplotlib\\__init__.py'
>>> import sip
>>> sip.__file__
'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sip.pyd'
```

Googling "tox fails with matplotlib" surprisingly did not lead me to anything useful. 

Here is the full error message:
```
======================================== test session starts =========================================
platform win32 -- Python 3.8.5, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
cachedir: .tox\py38\.pytest_cache
rootdir: C:\Users\scott\git\ixdat
collected 2 items

tests\test_dummy.py .F                                                                          [100%]

============================================== FAILURES ==============================================
_______________________________________ test_blank_measurement _______________________________________

    def test_blank_measurement():  # FIXME: tox can't handle matplotlib

>       from ixdat.measurements import Measurement

tests\test_dummy.py:10:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.tox\py38\lib\site-packages\ixdat\__init__.py:15: in <module>
    from . import plotters
.tox\py38\lib\site-packages\ixdat\plotters\__init__.py:1: in <module>
    from .value_plotter import ValuePlotter
.tox\py38\lib\site-packages\ixdat\plotters\value_plotter.py:3: in <module>
    from matplotlib import pyplot as plt
.tox\py38\lib\site-packages\matplotlib\pyplot.py:2336: in <module>
    switch_backend(rcParams["backend"])
.tox\py38\lib\site-packages\matplotlib\__init__.py:703: in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
.tox\py38\lib\site-packages\matplotlib\pyplot.py:256: in switch_backend
    switch_backend(candidate)
.tox\py38\lib\site-packages\matplotlib\pyplot.py:276: in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
.tox\py38\lib\site-packages\matplotlib\pyplot.py:277: in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
c:\programdata\anaconda3\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
.tox\py38\lib\site-packages\matplotlib\backends\backend_qt5agg.py:11: in <module>
    from .backend_qt5 import (
.tox\py38\lib\site-packages\matplotlib\backends\backend_qt5.py:16: in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
.tox\py38\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py:11: in <module>
    from matplotlib.backends.qt_compat import QtGui
.tox\py38\lib\site-packages\matplotlib\backends\qt_compat.py:170: in <module>
    _setup()
.tox\py38\lib\site-packages\matplotlib\backends\qt_compat.py:130: in _setup_pyqt4
    _setup_pyqt4_internal(api=2)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

api = 2

    def _setup_pyqt4_internal(api):
        global QtCore, QtGui, QtWidgets, \
            __version__, is_pyqt5, _isdeleted, _getSaveFileName
        # List of incompatible APIs:
        # http://pyqt.sourceforge.net/Docs/PyQt4/incompatible_apis.html
        _sip_apis = ["QDate", "QDateTime", "QString", "QTextStream", "QTime",
                     "QUrl", "QVariant"]
        try:
            import sip
        except ImportError:
            pass
        else:
            for _sip_api in _sip_apis:
                try:
>                   sip.setapi(_sip_api, api)
E                   AttributeError: module 'sip' has no attribute 'setapi'

.tox\py38\lib\site-packages\matplotlib\backends\qt_compat.py:113: AttributeError
====================================== short test summary info =======================================
FAILED tests/test_dummy.py::test_blank_measurement - AttributeError: module 'sip' has no attribute '...
==================================== 1 failed, 1 passed in 0.64s =====================================
ERROR: InvocationError for command 'C:\Users\scott\git\ixdat\.tox\py38\Scripts\pytest.EXE' (exited with code 1)
py39 create: C:\Users\scott\git\ixdat\.tox\py39
ERROR: InterpreterNotFound: python3.9
pypy3 create: C:\Users\scott\git\ixdat\.tox\pypy3
ERROR: InterpreterNotFound: pypy3
flake8 inst-nodeps: C:\Users\scott\git\ixdat\.tox\.tmp\package\4\ixdat-0.0.2.dev0.zip
flake8 installed: flake8==3.8.4,ixdat @ file:///C:/Users/scott/git/ixdat/.tox/.tmp/package/4/ixdat-0.0.2.dev0.zip,mccabe==0.6.1,pycodestyle==2.6.0,pyflakes==2.2.0
flake8 run-test-pre: PYTHONHASHSEED='971'
flake8 run-test: commands[0] | flake8
______________________________________________ summary _______________________________________________
ERROR:  py36: InterpreterNotFound: python3.6
ERROR:  py37: InterpreterNotFound: python3.7
ERROR:   py38: commands failed
ERROR:  py39: InterpreterNotFound: python3.9
ERROR:  pypy3: InterpreterNotFound: pypy3
  flake8: commands succeeded
```

**Comment by ScottSoren** [comment]
Brilliant suggestion by Alexander Krabbe to add `sip>=5.0` to requirements tried but still doesn't work.

Another strange result is that, even with that requirement, sip does not behave as expected when tox is running.
In anaconda prompt:
```
$ python

>>> import sip
>>> sip.SIP_VERSION
267021
>>>
```
But, the test
```
def test_sip_import():  

    import sip
    print(f"sip version = {sip.SIP_VERSION}")
```
fails when running tox with:

`E       AttributeError: module 'sip' has no attribute 'SIP_VERSION'`

So I'm pulling out hairs.

I found that this is an unsolved error for at least one other user: https://github.com/skelouse/mlframe/issues/2

**Comment by KennethNielsen** [comment]
Looks very unpleasant. I would suggest to disable the commit hook for now.

I will see if I can reproduce at home.

Only thoughts is that it would be nice with a print of the imported sip module, to see what it identifies it self as and where it is imported from.

The tests probably don't need matplotlib for anything else than to be imported, so a possible (although naughty) workaround would be to inject a Mock object into the cache of imported modules under the name matplotlib in the test setup... but I'm not sure that would work.

**Comment by ScottSoren** [comment]
Update:
I can't reproduce it either (I guess this is both good and bad news)

I'm on another computer (Spectro Inlets DELL). It is running Anaconda python 3.7 as the default python. The problem was on a computer (Imperial College HP Elitebook) running Anaconda python 3.8 as the default python. Both computers are Windows 10. However, tox passes in python 3.8 as well on the second computer!

SIDE NOTE: 
I've had a bit of trouble getting tox to identify the py38 interpreter. I created an environment called py38 with python=3.8 installed in Anaconda. Its python executable is `C:\Users\scott\Anaconda3\envs\py38\python.exe`. I added 
both `C:\Users\scott\Anaconda3\envs\py38\` and `C:\Users\scott\Anaconda3\envs\py38\Scripts` to the system PATH variable, which [should be enough](https://github.com/tox-dev/tox/issues/378#issuecomment-252956481). But still when I run tox in git bash, or Anaconda Prompt (base), it says InterpreterNotFound except for py37. Only if I run from Anaconda Prompt (py38) can it find both interpreters:
```
$ tox
...
___________________________________ summary ___________________________________
ERROR:  py36: InterpreterNotFound: python3.6
  py37: commands succeeded
  py38: commands succeeded
ERROR:  py39: InterpreterNotFound: python3.9
ERROR:  pypy3: InterpreterNotFound: pypy3
  flake8: commands succeeded
```
END SIDE NOTE.

I can also confirm that tox works now when called by the pre-push hook. 😄  . So I have at least one system from which I can run all the tools!

I wonder if the difference has to do with the tox installation or its environment management? I do remember you helped me set up tox on the computer where it works. I probably pip installed it on the other computer through Anaconda Prompt, but will check when in tomorrow. For my reference:
```
(base) C:\Users\scott\git\ixdat>conda list tox
# packages in environment at C:\Users\scott\Anaconda3:
#
# Name                    Version                   Build  Channel
tox                       3.15.2                   pypi_0    pypi

(base) C:\Users\scott\git\ixdat>conda list virtualenv
# packages in environment at C:\Users\scott\Anaconda3:
#
# Name                    Version                   Build  Channel
virtualenv                20.4.7                   pypi_0    pypi

(base) C:\Users\scott\git\ixdat>conda list pip
# packages in environment at C:\Users\scott\Anaconda3:
#
# Name                    Version                   Build  Channel
pip                       21.0.1                   pypi_0    pypi
```

Anyway, agree, if I can't solve it I will just disable git hooks on the problematic computer.

**Comment by KennethNielsen** [comment]
About terminal output, that's a good point. Because both pytest and tox captures output, that might be difficult. Rather that punching a whole through that, you can just write to file conveniently with print:

```terminal
(ixdat) PS C:\venv\ixdat\ixdat> python
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> f = open("output.txt", "w")
>>> from functools import partial
>>> print = partial(print, file=f)
>>> print("hello")
>>> print("world")
>>> f.close()
>>> exit()
(ixdat) PS C:\venv\ixdat\ixdat> cat .\output.txt
hello
world
```

As for the real problem, I'm wondering if anaconda is enough of a exotic python env that we are going to run into more problems with tox. What happens on the same machine, if you cut tox out of the equation, by changing the git push hook (in `.git/hooks/pre-push` to run:

```bash
..... Lot's of comments at the start
#
# This script should be copied or better yet sym-linked into .git/hooks/

invoke checks
exit $?
```

instead of 

```bash
..... Lot's of comments at the start
#
# This script should be copied or better yet sym-linked into .git/hooks/

invoke tox --single
exit $?
```

The command in itself seems to work well enough for the checks (although maybe it needs a "called_from_git" option that modifies the output a little to make it easier to tell the output of the checks from that from git. What we would loose by this is that checks don't get run in separate environments and in parallel, but maybe it is better if tox and anaconda is a bad combo. And we can still keep the tox config to run the tests in as many python environments as possible on the machines where it works.

**Comment by ScottSoren** [comment]
This is solved!
I needed to upgrade pip, and make sure pip was installed by pip and not by conda or something else.
```
(base) PS C:\windows\system32> conda list pip
      # packages in environment at C:\ProgramData\Anaconda3:
      #
      # Name                    Version                   Build  Channel
      pip                       20.2.4           py38haa95532_0
      
(base) PS C:\windows\system32> pip install --upgrade pip
      Collecting pip
        Using cached pip-21.1.3-py3-none-any.whl (1.5 MB)
      Installing collected packages: pip
        Attempting uninstall: pip
          Found existing installation: pip 20.2.4
          Uninstalling pip-20.2.4:
            Successfully uninstalled pip-20.2.4
            
(base) PS C:\windows\system32> conda list pip
      # packages in environment at C:\ProgramData\Anaconda3:
      #
      # Name                    Version                   Build  Channel
      pip                       21.1.3                   pypi_0    pypi.
```

After that, tox works in both git bash and Anaconda prompt. It requres a --recreate option the first time to force it to reinstall the py38 environment using the correct pip.

```
$ tox --recreate
      ...
      ___________________________________ summary ___________________________________
      ERROR:  py36: InterpreterNotFound: python3.6
      ERROR:  py37: InterpreterNotFound: python3.7
        py38: commands succeeded
      ERROR:  py39: InterpreterNotFound: python3.9
      ERROR:  pypy3: InterpreterNotFound: pypy3
      ERROR:   flake8: commands failed
```
