### ISSUE TITLE
calibration of sensitivity factor should be forced to 0

### ISSUE THREAD

**Issue by Caiwu-L** [ixdat/ixdat#109]
The current calibration doesn't go to 0, if use it to get the transient faradic efficiency, which always assume it goes to 0,  it doesn't match. Should force the linear fit to go through zero.

**Comment by ScottSoren** [comment]
@Caiwu-L , finally solved this, 8 months later (lots of distractions in the meanwhile!). I don't think it should always be forced through zero, but I've now implemented the option. Take a look at the code here (feel free to comment!): https://github.com/ixdat/ixdat/pull/135

**Comment by ScottSoren** [comment]
Solved by https://github.com/ixdat/ixdat/pull/135, to be released with 0.2.7
