### ISSUE TITLE
Combined Counter Electrode Potenial

### ISSUE THREAD

**Issue by BeneVolere** [ixdat/ixdat#110]
When importing EC data from biologic, some techniques have Ewe/V for potential and some have <Ewe>/V, ixdat can combine these into "raw_potential". However, there is no equivalent for counter electrode potential, this would be very useful to have.

**Comment by ScottSoren** [comment]
Thanks for this issue, @BeneVolere , which I'm finally solving 8 very distracted months later. See the code changes (and feel free to review!) here: https://github.com/ixdat/ixdat/pull/135

**Comment by ScottSoren** [comment]
Solved by https://github.com/ixdat/ixdat/pull/135, to be released with 0.2.7
