### ISSUE TITLE
Zilien spectra reader is not working

### ISSUE THREAD

**Issue by AnnaWiniwarter** [ixdat/ixdat#117]
There is a spelling mistake in the data exported by Zilien (`"Mass  [AMU]"` with a double space), while the reader expects this to be `"Mass [AMU]"` (single space). 
Also, when preparing the dict: it needs to be `"name": self.path_to_spectrum.name` rather than `"name": path_to_spectrum.name`

Note that I'm using the quant_integration branch, maybe this has been fixed elsewhere?

**Comment by AnnaWiniwarter** [comment]
ok, so the "Mass [AMU]" typo is fixed in main, the other one isnt

**Comment by ScottSoren** [comment]
Hey Anna, yeah, good catch! The "Mass 
 [AMU]" thing is fixed on main as you saw, and demonstrates the problem with a long-lived feature branch :( . Best to copy the implementation here to avoid merge conflicts: https://github.com/ixdat/ixdat/blob/6584d8978e8f78dce05c7ccf6ea3e5838814d4b5/src/ixdat/readers/zilien.py#L610
The other one I guess means no one has been importing spectra. What is supposed to happen with that is that Zilien, when there are spectra, returns a SpectroMSMeasurement: class SpectroMSMeasurement(MSMeasurement, SpectroMeasurement):
