### ISSUE TITLE
Executed EC-MS tutorial on documentation page misses code-text boxes

### ISSUE THREAD

**Issue by AnnaWiniwarter** [ixdat/ixdat#120]
I was made aware of this issue recently - apparently all the code got lost when converting the executed tutorial to a .rst file. I believe this was already mentioned in #113 but I didn't take care of it then.

**Comment by AnnaWiniwarter** [comment]
Turns out, the code is actually there in the file: docs/source/getting_started/tutorials/ecms_tutorial.rst
When I compile it locally, I also get the code pieces in the HTML file, but they are not on the compiled readthedocs page. Have you experienced something like this before @ScottSoren?

**Comment by ScottSoren** [comment]
Seems something is broken with the `.. code:: ipython3` command.
I think we should just use `::` instead. That's what the documentation for ipython itself does: https://raw.githubusercontent.com/ipython/ipython/main/docs/source/interactive/tutorial.rst

I'll look into whether this is configurable in nbconvert: https://nbconvert.readthedocs.io/en/latest/usage.html#restructuredtext

**Comment by ScottSoren** [comment]
I reproduce part problem: nbconvert puts the `code` directive instead of the (presumably) needed `code-block` directive. 

I suggest we try using nbsphinx instead: https://nbsphinx.readthedocs.io/en/0.9.3/index.html

**Comment by ScottSoren** [comment]
Solved with #127 :)
