### ISSUE TITLE
Does `MSInlet` belong in `ixdat`?

### ISSUE THREAD

**Issue by ScottSoren** [ixdat/ixdat#122]
Getting a calibration factor in [A]/[mol/s] = [C/mol] out of an experiment where a gas of known composition is flowed over a mass spec inlet requires a function for calculating the molar flux of analyte molecules through the inlet as a function of the gas composition, pressure, and temperature.
Right now ixdat has a `MSInlet` object which has that function in its `calc_n_dot_0` method. The equation used is for a Spectro Inlets (SI) chip. However, the SI chip is described authoritatively in the `spectro_inlets_quantification` (siq) package which has a `Chip` object with a method of the same name. The siq version is more powerful as it, for example, computes the viscosity of gas mixtures.

My thinking is that the code representation of the SI chip should live in siq, because the chip is made by SI. But this opens the question, where do gas flux calibration methods go?

Confusingly, ixdat at present has two methods that do the same thing, MSInlet.gas_flux_calibration which uses ixdat native stuff and MSMeasurement.gas_flux_calibration which uses siq stuff. That is not intuitive at all. [This behaviour is demo'd here](https://github.com/ixdat/ixdat/blob/696a0d763c16a11bfa072e2a835c69d61c3aba44/development_scripts/quant_integration_demo.py).

Reflecting that we know the present state is a mess, `MSInlet` is now deprecated. But how to replace it is not clear.

I can think of the following options:
1. ixdat has no native gas flux calibration. Existing gas flux calibration measurements are moved to siq.
2. ixdat has gas flux calibrations as methods of MSMeasurement but require siq as a plugin (as MSMeasurement.gas_flux_calibration, etc do now)*. The method returns an object defined in the plugin package.
3. ixdat has gas flux calibrations as methods of MSMeasurement which return the native MSCalResult object but require an MSInlet from an external package. Then ixdat needs to make a requirement on the interface with this MSInlet**
4. ixdat has (as now) a native MSInlet which defaults to the one we know

*What to do when/if other MS quantification plugins become available is a problem for then.
**i.e. any MSInlet has to have a calc_n_dot method which takes some specific set of arguments and returns a float in mol/s.

Maybe it would be best for now to just delete the calibration methods in MSInlet and have the calibration methods in MSMeasurement behave differently based on whether siq is active, like ECMSMeasurement.ecms_calibration etc already do?

And I think `ixdat.plugins.si_quant` (maybe should be renamed `ixdat.plugins.siq`?) should have methods that convert between `ixdat.techniques.ms.MSCalResult` and `spectro_inlets_quantification.calibration.CalPoint` , etc.

**Comment by KennethNielsen** [comment]
I think I better understand the problem now and I think my previous comments on the matter were a little confusing.

First of, we can totally agree that having similarly named methods on different objects perform similar actions is not the way to go. However, I don't see the need to loose ixdat's internal methods for quantification, as it has some merit that you can get started without dealing with an external dependecy.

What I would suggest is the MSMeasurement simple has one method per quantification route and the name prefix to indicate the souce, like `gas_flux_calibration_native` and `gas_flux_calibration_siq`. The latter will of course depend on the plugin. This approach also means that you can convert the resulting siq calibrations to ixdat calibrations, avoiding that whole mess. **And** since there are now two methods, there will be no confusiong about taking different arguments, like of e.g. the siq one will take a chip name/id or alternatively chip kana dimensions.

**Comment by alkrSTATGL** [comment]
I agree with @KennethNielsen that having an internal method for quantification is good. 

One major advantage of using IXDAT for thermal / photo microreactor-MS is the quantification part.
I might be missing the point but missing the internal quantification part of IXDAT would make the package less usefull.

Having to rely on an external package to begin using quantification in IXDAT seems like an unnessecary obstacle.

However, I did not use the si_quant package that much so I might be missing the point of this post and how much impact removing MSInlet will have.

**Comment by ScottSoren** [comment]
Thanks for the comments here and discussions elsewhere about this! 
We'll do as @KennethNielsen suggests, moving the native MS calibration functions over to `MSMeasurement` and giving the siq one a different name. `MSInlet` will stay. PR coming soon.

Duplication of molecule data between ixdat and siq was a related issue. @KennethNielsen suggested the possibility that both siq and ixdat rely on a common separate package for it. Such a package could make optional use of [NistChemPy](https://pypi.org/project/NistChemPy/)
