### ISSUE TITLE
Typo in "BOLTZMAN_CONSTANT"

### ISSUE THREAD

**Issue by AnnaWiniwarter** [ixdat/ixdat#125]
Dont want to be overly nitpicky here, but Boltzmann is spelled with a double "n" and so is the constant named after him :)
https://github.com/ixdat/ixdat/blob/0d7e1e34c7021c68119e1817ee11d81cf5545d99/src/ixdat/constants.py#L23C1-L23C23

**Comment by ScottSoren** [comment]
fixed.
