### ISSUE TITLE
`SpectrumSeries.heat_plot()` assumes even spacing between spectra

### ISSUE THREAD

**Issue by ScottSoren** [ixdat/ixdat#140]
This can result in misleading heat plots if the timing of the spectra was not evenly spaced. Either there should be a warning, or the method should check and do some interpolation before giving an array to matplotlib's `imshow`.
Spot in source code: https://github.com/ixdat/ixdat/blob/9efe4fb318a01c65444690d2f5541e165b528ad2/src/ixdat/plotters/spectrum_plotter.py#L138

**Comment by AlexanderKrabbe** [comment]
This issue is omehow related to how heatplot is used for MSSpectrums versus temperature / pressure instead of time. There the spacing is not equal.
