### ISSUE TITLE
when giving mass_lists in plot_vs_potential in ecms plotter, masses on secondary axes are plotted together with EC instead of MS subplot

### ISSUE THREAD

**Issue by spoeka22** [ixdat/ixdat#16]
Bug seems to be located in ecms_plotter, line 216 (i.e. in the def for plot_vs_potential). It can be fixed when changing "axes[2]" to "axes[3]".

**Comment by ScottSoren** [comment]
But axes[2] shouldn't be there at all, haha, as you discovered in #19 . 
The problem was in line 204 - no need for `n_bottom=2` with `plot_vs_potential`. 
This is now solved on the [fuzhou] branch.
