### ISSUE TITLE
MSMeasurement.siq_multicomp_gas_flux_calibration gives results inconsistent with MSMeasurement.gas_flux_calibration!

### ISSUE THREAD

**Issue by ScottSoren** [ixdat/ixdat#160]
For example a 30% difference in F^O2_M32 based on N2 with 20% O2, compared to multicomp_gas_calibration. The difference is not explained by the viscosity of air, which is only 3.5% different from that of N2 at room temperature.

**Comment by KennethNielsen** [comment]
@matenestor I think this should be on your list, either for after the current project or at least for tracking.

**Comment by ScottSoren** [comment]
@AnnaWiniwarter , I think we solved this, right? Is the correction merged?

**Comment by AnnaWiniwarter** [comment]
Yes! I've been using it, works fine now.
