### ISSUE TITLE
Overlapping axis using ECMS plotter? - New update

### ISSUE THREAD

**Issue by abhadou** [ixdat/ixdat#161]
Hi,
This might be a trivial question, but I have worked on the issue for a while and not sure how to resolve it. I recently updated my python, ixdat, anaconda systems and am now facing this issue of double/overlapping axis when using `ecms.plot_measurement()` (image attached of code below)

![image](https://github.com/ixdat/ixdat/assets/125094181/655160e5-97d1-4f2f-8abb-bc9e7601ca56)

When I go on the[ ixdat tutorial website](https://ixdat.readthedocs.io/en/latest/tutorials/tutorials_repo/L2_techniques/ec_ms_quantification/ixdat_demo_EC-MS.html#Importing,-plotting,-and-exporting) this warning pops up too: 

```
C:\Users\Søren\git\ixdat\src\ixdat\plotters\base_mpl_plotter.py:61: MatplotlibDeprecationWarning: Auto-removal of overlapping axes is deprecated since 3.6 and will be removed two minor releases later; explicitly call ax.remove() as needed.
  axes = [plt.subplot(gs[0:3, 0])]
```

I think this might be the issue. It seems matplotlib has deprecated auto-overlap removal of axes and some form of `axes.remove()`,` axes.clf()`, `axes.set_yticks([])` might be needed in the source code for the plotter in order to clear the axes underneath? I tried clearing once it plots, however, since the third output of the plotter is actually a "None", these functions don't work on these and I get a `'NoneType' object has no attribute 'set_yticks'` error. I tried providing it axes to plot as well and it doesnt seem to work. 

Help on this matter is greatly appreciated!

Python version: 3.10.1
ixdat version: 0.2.8

**Comment by ScottSoren** [comment]
Hi @abhadou , 

Thanks for this! I just updated matplotlib to reproduce and solve the error. (Maybe I shouldn't just ignore DeprecationWarnings from dependencies!) 

Luckily it's an easy fix, just needed to initiate a fig [without an ax ](https://github.com/ixdat/ixdat/blob/a00c49c358a0a50f0755996a491a7e4a3b290c1e/src/ixdat/plotters/base_mpl_plotter.py#L56) before setting up the gridspec. (The hint for me came from @AnnaWiniwarter using gridspec correctly in [this tutorial](https://github.com/ixdat/ixdat/blob/a00c49c358a0a50f0755996a491a7e4a3b290c1e/src/ixdat/plotters/base_mpl_plotter.py#L56).)

It's available now on the [spectromeasurement] branch, and the pre-release [ixdat 0.2.9.dev2](https://pypi.org/project/ixdat/0.2.9.dev2/) 
The full release will come following review and merge #166 .
