### ISSUE TITLE
Noisy EC data when importing from Zilien tsv, cannot be replaced by adding biologic files

### ISSUE THREAD

**Issue by spoeka22** [ixdat/ixdat#17]
When importing Zilien, an ECMSMeasurement is created, which makes a lot of sense. However, (at the moment), EC data is sampled differently in Zilien, which in some cases can mean that the EC data is more noisy than in the corresponding biologic file. When using the biologic reader and adding this ECMeasurement to the ECMSMeasurement (using the '+' operator), it seems that the EC columns are not replaced, but instead added (which makes sense). When then plotting the resulting ECMSMeasurement using .plot_measurement, however, this results in the "raw potential" and "raw current" somehow being the two different EC measurements lying on top of each other (the length of the "grabbed" array is also higher in the combined Measurement than the original one even if cutting to the same t_span).

**Comment by ScottSoren** [comment]
I've enabled a way to do this (the update is on the [fuzhou] branch). If you read zilien specifically as an `MSMeasurement`, it will now leave out the EC stuff. Then you can add it in from the .mpt's. 

```
from ixdat import Measurement

meas = Measurement.read("my_file.tsv" , reader="zilien"
meas.plot()  # two panels, top has MS and bottom has noisy EC

from ixdat.techniques.ms import MSMeasurement

meas = MSMeasurement.read("my_file.tsv" , reader="zilien"
meas.plot()  # just one panel, with MS data. No EC data to be found
```

See this more example (switch out the files with your files): https://github.com/ixdat/ixdat/blob/Fuzhou/development_scripts/reader_testers/test_zilien_reader.py

Hopefully this also solves #20

**Comment by spoeka22** [comment]
Importing only MS data from the Zilien file and biologic data solves this issue (and also #20 ). I close this issue now, even though the actual issue described (which EC current/potential is prioritized when adding a biologic imported EC object to a Zilien imported ECMS object?) is not actually solved (but it's not longer a problem in my workflow).
