### ISSUE TITLE
right y-axis in EC plot in plot_vs_potential

### ISSUE THREAD

**Issue by spoeka22** [ixdat/ixdat#19]
When using plot_vs_potential (of data imported using Zilien importer) a right y-axis is created but nothing is added to it, so a scale from 0 to 1 is shown without axis label. 
![image](https://user-images.githubusercontent.com/32706572/143278625-7058e544-a87e-4b67-9dff-941f30851ced.png)

**Comment by ScottSoren** [comment]
see #16 .
