### ISSUE TITLE
Voltammagram/voltammogram spelling issue

### ISSUE THREAD

**Issue by spoeka22** [ixdat/ixdat#23]
I noticed that in the code both voltammagram (with an "a", incorrect spelling) and voltammogram (with an "o", the correct spelling) are being used. I understand that changing all the incorrectly spelled occurrences might be a problem for backwards compatibility, but having both spellings in there in different places is a bit confusing. :)

_Originally posted by @spoeka22 in https://github.com/ixdat/ixdat/issues/22#issuecomment-982489980_

**Comment by ScottSoren** [comment]
Fixed everyewhere I found it.

**Comment by KennethNielsen** [comment]
@ScottSoren with the new deprecation decorator, we could supply a backwards compatibility fix for the class name as easy as:
```python
Voltammagram = deprecate("0.1.9", "Please use the class `Voltammogram` instead (notice correctly spelled name)")(Voltammogram)
```
after the class definition, but I don't know if it is really worth it or if so few are using it at this point that it is wasted effort.
