### ISSUE TITLE
Enable customizable importing from a zilien tsv file

### ISSUE THREAD

**Issue by AnnaWiniwarter** [ixdat/ixdat#31]
In addition to the columns deemed relevant by ixdat, I would like to import some extra columns with process parameters (like pressures etc) from a zilien datafile to then co-plot this with the MS signals (eg. instead/in addition to the EC data). 
The current solution of using and EC-MS importer for importing zilien files makes it a bit difficult to figure out if/how this is already possible somehow.

**Comment by AnnaWiniwarter** [comment]
I just ran into this issue again, that I would like to select whether I want to just import EC data or just MS data from a Zilien file. This time I wanted to add EC-Lab EC data to Zilien MS data. This is possible by replacing the EC data using `.replace_series()`, but this is really not straightforward. And its not very intuitive that if I use `MSMeasurement.read(myfile.tsv, reader="zilien")` it imports BOTH the EC and the MS data as an `MSMeasurement` object where the EC data suddenly re-appears when converting it to an ECMSMeasurement object when adding some additional EC data...

**Comment by KennethNielsen** [comment]
These are all good points. About the process parameters, @ScottSoren I noticed a lot of "I've ignore this column" when parding these files. Are they ignored on purpose, because you don't want other data series in there than the MS and EC, or is it merely a matter of not implemented yet. Because those columns don't contain any data that isn't easily represented as the same Time and ValueSeries as the rest?

**Comment by AnnaWiniwarter** [comment]
Another weird discovery (that surely makes perfect sense in the code): When I explicitly ask to import the Zilien file as an EC file using `ixdat.techniques.ec.ECMeasurement.read(myfile.tsv, reader="zilien")` I still get an `MSMeasurement` object (not an `ECMSMeasurment` object!) and no warnings...

**Comment by KennethNielsen** [comment]
> Another weird discovery (that surely makes perfect sense in the code): When I explicitly ask to import the Zilien file as an EC file using `ixdat.techniques.ec.ECMeasurement.read(myfile.tsv, reader="zilien")` I still get an `MSMeasurement` object (not an `ECMSMeasurment` object!) and no warnings...

Hmm. Seems there's a bit to look at there. I actually have "Rewriting the Zilien parser for ixdat" in this sprint (it is currently using the one from ECMS for the raw parsing), so hopefully we can clear some of this out.

**Comment by KennethNielsen** [comment]
This is auto closed by a recent commit on #68 which should fix it.
