### ISSUE TITLE
ReadError "Couldn't parse timestamp" when trying to read biologic file

### ISSUE THREAD

**Issue by AnnaWiniwarter** [ixdat/ixdat#33]
When trying to read biologic file, I encountered following error (see screenshot). 

![image](https://user-images.githubusercontent.com/96479350/152137272-48adacd9-fbda-4ebf-8094-db1c2ad814af.png)

It seems that when exporting as .mpt, depending on local computer settings, the timestamp format will be different. In this case, it was mm/dd/yyyy hh.mm.ss which lead to the error. 
(exporting the file on a different computer/manually editing the mpt file and changing the format to mm/dd/yyyy hh:mm:ss solved the issue)

**Comment by ScottSoren** [comment]
I'm adding `"%m/%d/%Y %H.%M.%S"` to the variable `BIOLOGIC_TIMESTAMP_FORMS` in the biologic module. Should import now.
