### ISSUE TITLE
Import error for incomplete sets?

### ISSUE THREAD

**Issue by KimDegnJensen** [ixdat/ixdat#38]
If EC experiment fails before completion and no full cycles are available importing in ixdat produces error

**Comment by KennethNielsen** [comment]
Can you provide a set of data files and code example that fails?

**Comment by KimDegnJensen** [comment]
importing this gave some weird issues for me. KR Kim

**Comment by KennethNielsen** [comment]
@KimDegnJensen  I don't think the attachment made it to GitHub. Can you post the there and also the code you use to load it with?

**Comment by ScottSoren** [comment]
Closing this, as it's a few ixdat versions old and possibly related to #93 . @KimDegnJensen , please reopen if there's still an issue here.
