### ISSUE TITLE
Download cinfdata with EC_MS and use in MSmeasurement raise IndexError and SeriesNotFoundError 

### ISSUE THREAD

**Issue by AlexanderKrabbe** [ixdat/ixdat#41]
maybe i have misread how to add ms data.

I downlad data with the EC_MS downloader:

data = download_cinfdata_set(setup='microreactorNG', time='2022-03-12 19:54:01')

I then use MSMeasurement to create an ms object

ms = MSMeasurement(data)

However when running t, S = ms.grab(signal_name = 'M44'), 

I recieve and IndexError: list index of of range

`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_8116/1536563656.py in <module>
----> 1 t, S = ms.grab_signal(signal_name='M44-y')

~/ixdat/ixdat/src/ixdat/techniques/ms.py in grab_signal(self, signal_name, tspan, tspan_bg, removebackground, include_endpoints)
    105             include_endpoints (bool): Whether to ensure tspan[0] and tspan[-1] are in t
    106         """
--> 107         time, value = self.grab(
    108             signal_name, tspan=tspan, include_endpoints=include_endpoints
    109         )

~/ixdat/ixdat/src/ixdat/measurements.py in grab(self, item, tspan, include_endpoints, tspan_bg)
    490                 subtracted from the values returned.
    491         """
--> 492         vseries = self[item]
    493         tseries = vseries.tseries
    494         v = vseries.data

~/ixdat/ixdat/src/ixdat/techniques/ms.py in __getitem__(self, item)
     61         """Try standard lookup, then check if item is a flux or alias for a mass"""
     62         try:
---> 63             return super().__getitem__(item)
     64         except SeriesNotFoundError:
     65             if item in self.mass_aliases:

~/ixdat/ixdat/src/ixdat/measurements.py in __getitem__(self, item)
    429                 s = ss[0]
    430             else:
--> 431                 s = append_series(ss)
    432         else:
    433             raise SeriesNotFoundError(f"{self} has no series called {item}")

~/ixdat/ixdat/src/ixdat/measurements.py in append_series(series_list, sort, tstamp)
    856         tstamp (unix tstamp): The t=0 of the returned series or its TimeSeries.
    857     """
--> 858     s0 = series_list[0]
    859     if isinstance(s0, TimeSeries):
    860         return append_tseries(series_list, sort=sort, tstamp=tstamp)

IndexError: list index out of range
`

**Comment by ScottSoren** [comment]
Hey Alexander. First of all, awesome. ixdat needs a cinfdata downloader of its own, see comment here:
That's in ixdat/readers/cinfdata.py, a module which so far just reads cinfdata text exports. You could use that of course, but in the meanwhile using the old `EC_MS` downloader and then getting it into ixdat is a great idea!
To do so, try using ixdat's EC_MS converter via the following code:

```
from EC_MS import download_cinfdata_set
from ixdat.techniques import MSMeasurement
from ixdat.readers.ec_ms_pkl import measurement_from_ec_ms_dataset

old_dataset = download_cinfdata_set(...)
meas = measurement_from_ec_ms_dataset(
    old_dataset, 
    cls=MSMeasurement,
    technique="MS"
)
meas.plot()
```
I can't test this code myself because I don't have access to cinfdata, but if can give it a try and let me know what error it hits, I'm sure we can work thourh it.

**Comment by AlexanderKrabbe** [comment]
Fantastic. This seem to work out of the box. I will close and reopen if i hit any errors along the way. 

I was trying to find a way to save as pickle and load as pickle using EC_MS like [here](https://github.com/ScottSoren/pyCOox_public/blob/main/paper_II_fig_3/paper_II_fig_3.py)

**Comment by ScottSoren** [comment]
Great to hear! :) 
Yeah, I guess that could work too. This way saves making the .pkl though.

**Comment by ScottSoren** [comment]
I think that's up to the person who writes it ;) 
It'll be the first `Reader` which is actually a downloader. But I think that doesn't make any difference to the way it "plugs in", so the cinfdata text reader could be a fine template.

**Comment by KennethNielsen** [comment]
> Would one implement such a class in the existing cinfdata.py reader or would it go into a new cinfdata_db.py reader?

In terms of segmentation of code I would cautiously suggest a separate file. So that the files are one-reader-per-file and not one-source-per-file, as I find the first easier to reason about.
