### ISSUE TITLE
Set a changing background in an `MSMeasurement`

### ISSUE THREAD

**Issue by ScottSoren** [ixdat/ixdat#78]
A request from Daisy. 
Sometimes MS spectrometer sensitivity drifts significaantly over the course of a long experiment. It would be nice to be able to say, for example,
`ms.set_linear_background(tspan_1, tspan_2)` 
and then have subsequent calls of 
`ms.plot(..., logplot=False)` 
by default plot signals or masses with a background subtracted such that the average values during `tspan_1` and `tspan_2` are set through zero.

**Comment by KennethNielsen** [comment]
This case would also be fairly easy to implement by [this proposal](https://github.com/ixdat/ixdat/issues/79#issuecomment-1194136986)

**Comment by ScottSoren** [comment]
Duplicate of #79 , will solve there.
