### ISSUE TITLE
Use a background found elsewhere in calibration functions

### ISSUE THREAD

**Issue by ScottSoren** [ixdat/ixdat#79]
Right now the only way to define a background value in calibration functions like `MSInlet.gas_flux_calibration` is by using `tspan_bg`. This means that there has to be a background signal measurement in the same `MSMeasurement` as the calibration. However, what if I have the background value from elsewhere? I might want to do this:

```
M2_bg = np.mean(my_background_measurement.grab("M2")[1])
cal_H2_M2 = my_chip.gas_flux_calibration(my_real_measurement, mol="H2", mass="M2", bg=M2_bg, ...)
```
where the key-word argument here called `bg` is not presently implemented.

**Comment by AnnaWiniwarter** [comment]
I tried to look into this to see if I can take care of this when adding a `gas_flux_calibration_curve()` (issue #80) (I might, but it's not as directly related as I hoped)
- do I understand correctly that `set_bg()` is like a calibration for a set of data that will overrule any tspan_bg you pass basically do any function that then uses grab() to get the signal?

**Comment by ScottSoren** [comment]
Hi Anna,
Having called `set_bg` _does not_ override use of `tspan_bg` in other functions. It just sets a "default background" to be subtracted when background subtractied or implied and no `tspan_bg` is given.
By "implied" here I mean when the plotting function thinks that the user wants a background subtracted. Code is more precise than words, so here's that bit in `ECMSPlotter.plot_measurement`:
```
        if remove_background is None:
            remove_background = not logplot
```
So the user can request the default (preset with `set_bg`) background be removed if and only if the user calls the function with `remove_background=True` (by default it is `None`) OR `logplot=False` (by default it is `True`). Explicitly saying `remove_backgorund=False` also turns it off whether or not a logplot is requested.

An important bit is that the background determined by `set_bg` carries over when you chop up the measurement (for example by indexing an `ECMSCyclicVoltammogram` to select a cycle), even if that means losing the section with the tspan used for the original `set_bg`.

I noticed a problem while testing `set_bg` now to make sure I answer right: there's no way to unset it. `reset_bg()`, which should do this, seems to be broken. I'll open a different issue for this.

However, `set_bg` does not solve the original Issue here, becuase it can also only define a background from a `tspan_bg`. It does not give a user a chance to manually define the background signal.

**Comment by AnnaWiniwarter** [comment]
Hi Soren, 
Thanks for the thorough explanation.
I don't think I will try and do a quick&dirty solution for now, then. I had a discussion with Kim today who was also interested in getting #12 solved, so I think it's more meaningful that I do my calibration function now just using what is already implemented  and take up the bigger task of writing MSBackground later (I like the class-idea! but I hate the idea of me writing it).

**Comment by KennethNielsen** [comment]
@ScottSoren I didn't completely grasp the scope of this, so this suggestion might be silly but I'll give it a go.

I'm always a little worried about the complexity of our class tree and whether it is always the best tool for the job i.e. if we are adding . How about, here instead, making it possible to provide the background as a callable (function or method), which takes the t-series as argument 1 (and possibly the entire experiment as variable 2)* and then provides a background for the t-series, which has a background value for every point in the t-series. Any e.g. calibrations that should be able to provide a background, can then just do it by providing a method that calculates it or, if a user wants to hack some custom background, could just write the necessary functions.

And, unless you want to special case multi-point background definitions, it would be trivial to write a utility that creates the callable as a simple linear interpolation. Makes sense?

* Providing the entire experiment as argument 2 provides the option for creating callables that calculates the background using more data form the experiment if that is required.

**Comment by ScottSoren** [comment]
We have another `Background` calculator hidden in [plotting_tools.py](https://github.com/ixdat/ixdat/blob/1f60bd50c38b2effa7657e51a895156d183fdf7e/src/ixdat/plotters/plotting_tools.py#L77).
