### ISSUE TITLE
Using "axes_measurement" to pass an axis to MSInlet.gas_flux_calibration_curve() broken

### ISSUE THREAD

**Issue by AnnaWiniwarter** [ixdat/ixdat#94]
When passing an axis to MSInlet.gas_flux_calibration_curve() using axes_measurment, this should highlight the signal over the tspan selected to calculate the calibration. It doesn't work, however, when using the option of using a certain concentration in a carrier gas. Must have something to do with how the highlighted part is generated, seems it calculates the flux somehow?

**Comment by AnnaWiniwarter** [comment]
I haven't tested it, but I would guess the same goes for single point gas calibrations.

**Comment by KennethNielsen** [comment]
Any chance you can provide a working example and data that reproduces the bug?

**Comment by ScottSoren** [comment]
There's an example here: https://github.com/ixdat/tutorials/blob/new_ecms_tutorials/ec_ms_quantification/EC-MS_ixdat_tutorial.ipynb

**Comment by ScottSoren** [comment]
fixed.
