### ISSUE TITLE
Have to specify `techniuqe="MS"` when loading Zilien ".tsv" without EC data

### ISSUE THREAD

**Issue by ScottSoren** [ixdat/ixdat#95]
Code we would like to work:
```
ms_meas = Measurement.read("path/to/my/zilien_ms_file_without_ec_data.tsv")
ms_meas.plot()
```
However, we instead get the error:
```
ixdat.exceptions.SeriesNotFoundError: <ixdat.readers.zilien.ZilienTSVReader object at 0x000002AC1227F550> loaded without ECMSMeasurement essential series 't'
```
It works if we add `technique="MS"` to the call to read, but it is desired to not need that.

This is especially desired now in ixdat 0.2.4, where the reader is not needed for known file extensions like ".tsv", so that we only need the file name in `Measurement.read()`.

**Comment by matenestor** [comment]
Fixed in #159
