### ISSUE TITLE
You have to give at least one axis in ms_plotter if mass/mol_lists is used

### ISSUE THREAD

**Issue by AlexanderKrabbe** [ixdat/ixdat#97]
The function _parse_overloaded_inputs in ms_plotter.py 
https://github.com/ixdat/ixdat/blob/main/src/ixdat/plotters/ms_plotter.py#L289 

looks for 

https://github.com/ixdat/ixdat/blob/main/src/ixdat/plotters/ms_plotter.py#L331 
```
v_vlists:
    axes = axes or [ax, twinx()]
``` 

before looking for 

https://github.com/ixdat/ixdat/blob/main/src/ixdat/plotters/ms_plotter.py#L383 
```
if not ax:                                                                        
    ax = (                                                                        
             axes[0]
             if axes
             else self.new_ax(ylabel=f"signal / [{unit}]", xlabel="time / [s]")
    )
```

Is it by design?

Or could the latter be placed before v_lists to ensure creation of a new axis if none is given before creating a ax.twinx()?

**Comment by ScottSoren** [comment]
I think this is resolved after merging #102 :)
